RVNE_PATCHES_JAR="test"
RV_PATCHES_JAR="test2"
build_youtube() {
	RV_PATCHES_JAR_BAK=$RV_PATCHES_JAR
	RV_PATCHES_JAR=$RVNE_PATCHES_JAR
	echo $RV_PATCHES_JAR
	RV_PATCHES_JAR=$RV_PATCHES_JAR_BAK
}
build_youtube
echo $RV_PATCHES_JAR
